### ISSUE TITLE
Raceless concurrent migrator for SQL Server

### ISSUE THREAD

**Issue by n8allan** [canton7/Simple.Migrations#10]
"There is a race if this table doesn't exist and two migrators try and create it at the same time: this cannot be avoided."

SQL Server supports something called [app locks](https://msdn.microsoft.com/en-us/library/ms189823.aspx?f=255&MSPPError=-2147217396), which are simply named locks.  This would provide a really simple means to ensure no race conditions.

**Comment by canton7** [comment]
Aha! In all my hours of googling, I missed that. Thanks for the pointer!

**Comment by canton7** [comment]
(Re-opening until I next release)

**Comment by n8allan** [comment]
You're welcome.  :-)

**Comment by canton7** [comment]
Released
