### ISSUE TITLE
Different Database migrations in same assembily

### ISSUE THREAD

**Issue by generik0** [canton7/Simple.Migrations#11]
Hi

It would be very nive if one could have a migration filter of some sort, so the same assembily could have migrations for different databases and database connections.

I can use the DB object in the migration base for some filtering. But e.g. an attribute filter would be cool.
Ideas?

**Comment by canton7** [comment]
[Write your own `IMigrationProvider`](https://github.com/canton7/Simple.Migrations#finding-migrations).
