### ISSUE TITLE
Sql Server command timeout issue

### ISSUE THREAD

**Issue by jlandersen** [canton7/Simple.Migrations#14]
Hi

We have an issue with sql server command timeout. It seems that it uses default timeout when running migrations:
https://github.com/canton7/Simple.Migrations/blob/master/src/Simple.Migrations/Migration.cs#L64
The command timeout ends up with default 30 seconds.
It would nice to have the option of configuring this for a migration.

We work around it right now by overriding Execute in the migration. So this is a nice-to-have, not a need-to-have :)

**Comment by canton7** [comment]
Fair point: the timeout is configurable on the database provider, and it makes sense that it's used in the migration as well.

**Comment by canton7** [comment]
Does that look OK from your perspective?

**Comment by jlandersen** [comment]
Thumps up from here

**Comment by canton7** [comment]
Cool, I'll release that soon. Thanks for your input!
