### ISSUE TITLE
Making seeders

### ISSUE THREAD

**Issue by MajedDH** [canton7/Simple.Migrations#19]
if the migration would have seeders to populate the tables with auto generated data for testing it would be wonderful , like the seeder in Laravel 
https://laravel.com/docs/5.3/seeding

**Comment by canton7** [comment]
I see migrations and seeding as orthogonal issues: you run the migrations, then you do the seeding. In its simplest form, seeding is just running some SQL, which you can easily do by running a method after you finish your migrations. In more complex forms, it involves automatically generating sensible-looking records, which is a rabbit hole I don't want to get down.

Where you have a migration framework which is integrated into your ORM, it can make sense to integrate a seeding framework, as it can make use of the SQL-generation capabilities of the ORM. However, that's not applicable to Simple.Migrations.

Overall, I'm afraid I don't think that it makes much sense to bolt a seeding framework onto Simple.Migrations - there's nothing to be gained, and it goes against the "Simple" bit.
