### ISSUE TITLE
How to use description atribute?

### ISSUE THREAD

**Issue by andregr15** [canton7/Simple.Migrations#21]
How to use description atribute?

I tryed this but does not worked.

[Migration(1)]
[Description("migration 1")]

**Comment by canton7** [comment]
To be fair, I guess this isn't in the README...

```csharp
[Migration(1, "Migration 2")]
public class Migration1 : Migration
{

}
```

**Comment by andregr15** [comment]
Thanks man, works fine and sorry for the trouble.

**Comment by canton7** [comment]
Turning this into an issue to add this to the README
