### ISSUE TITLE
low priority details

### ISSUE THREAD

**Issue by splite** [canton7/Simple.Migrations#26]
I was downgrading Simple.Migrations to .net 4.0 (pretty easy btw, just bunch of `string.Format()` with a pinch of `if (foo != null)` and found some... details... 😄 All of them are candidates for "wont fix" (and thats fine 👍 )

### `MigrationNotFoundException` and  `MissingMigrationException` are implemented differently

the first one is using this.Data, the second is not (+ is missing `name="missingVersion"` in parameter comment)

```
/// <summary>
/// Exception thrown when migration data is missing
/// </summary>
/// <remarks>
/// This happens if SimpleMigrator finds that the database is at a particular version, but can't find
/// a migration with that version.
/// </remarks>
public sealed class MissingMigrationException : MigrationException
{
  /// <summary>
  /// Gets the version that migration data could not be found for
  /// </summary>
  public long MissingVersion
  {
    get { return (long)Data["MissingVersion"]; }
  }

  /// <summary>
  /// Instantiates a new instance of the <see cref="MissingMigrationException"/> class with the given missing version
  /// </summary>
  /// <param name="missingVersion">Version that migration data could not be found for</param>
  public MissingMigrationException(long missingVersion)
    : base("Unable to find a migration with the version" + missingVersion)
  {
    Data["MissingVersion"] = missingVersion;
  }
}
```
(please note this code is .net 4.0 !)

### IDatabaseProvider generic can be covariant
(ok, this one is nitpicking 😄 ) I am pretty sure `IDatabaseProvider<TConnection>` can be declared as covariant `IDatabaseProvider<out TConnection>`

### Embedd resource scripts
Would be nice to execute embedd resource script right away from `Migration` class (its only one simple helper method):

in Migration.cs:
```
/// <summary>
/// Run embedded script
/// </summary>
/// <param name="resourceIdentificator">in format your.namespace.file.extension</param>
public void EmbeddedScript(string resourceIdentificator)
{
  using (Stream stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(resourceIdentificator))
  {
    using (StreamReader reader = new StreamReader(stream))
    {
      Execute(reader.ReadToEnd());
    }
  }
}
```
(please note this code is .net 4.0 !)

**Comment by splite** [comment]
PS: Right now i have only VS2012 installed, so i can not prepare Pull Request for you.

**Comment by canton7** [comment]
Thanks!

It's true that IDatabaseProvider *can* be covariant, however I don't see any reason to make it covariant, and it's possible it may need to be modified to take a TConnection at some point in the future.

For running SQL from embedded resources, bear in mind that the resource might not be in the executing assembly. I think I'd rather people solve this use-case by subclassing Migration, and adding whatever methods they want to run embedded scripts, magically figure out the names of resources from some parameters, etc -- it's not a lot of code for users to write, and it gives them ultimate control.

**Comment by splite** [comment]
Ok, all your points are valid :) Thanks for your work & cool framework :)
