### ISSUE TITLE
Support for filters

### ISSUE THREAD

**Issue by jackjwilliams** [canton7/Simple.Migrations#29]
Thanks for this library! It would be nice if you could supply a filter func for filtering certain migrations. Use case:

In the Migrations\Update folder
```
public class Update_CreateStateTable : Migration {
... // Do "updatey" stuff (create tables, rename columns, etc..)
}
```

In the Migrations\Seed folder
```
public class Seed_States : Migration {
...// Seed all states
}
```

In the Migrations\TestData folder
```
public class Test_Users : Migration {
...// Seed all test users
}
```

Then I could provide the following filters to run different scenarios:

This would run only my Update scripts
`Func<string, bool> filterOutSeedAndTestScripts = x => !x.Contains("Seed") && !x.Contains("Test");`

This would run only my Seed scripts
`Func<string, bool> filterOutTestAndUpdateScripts = x => !x.Contains("Update") && !x.Contains("Test");`

This would run only my Test scripts
`Func<string, bool> filterOutSeedAndUpdateScripts = x => !x.Contains("Update") && !x.Contains("Seed");`

**Comment by canton7** [comment]
Can you do this with [a custom `IMigrationProvider`](https://github.com/canton7/Simple.Migrations#finding-migrations)?

**Comment by canton7** [comment]
Note that the framework isn't really suited to seed scripts or test data -- it expects to see a linear sequence of migrations, and it expects to be able to undo each and every one of them.  That's not really the case with seed / test data -- you might apply one set of seed data, or you might apply another set: you don't incrementally build up the seed data over the course of many migrations. 

I would do seeding by executing scripts against the database outside of the migration framework.

**Comment by jackjwilliams** [comment]
Yeah I thought about it afterwards (about how it would work with the linear progression), it wouldn't fit well with the typical model. Thanks for the response, I will probably just ramp up a little custom library to handle  seed / test data.

**Comment by canton7** [comment]
If you end up publishing something, let me know and I can link to it - I've had a couple of other people ask about seeding too.
