### ISSUE TITLE
ILogger.EndSequence "to" parameter called with wrong migration data

### ISSUE THREAD

**Issue by fubar-coder** [canton7/Simple.Migrations#31]
The call of `ILogger.EndSequence` in [SimpleMigrator<TConnection, TMigrationBase>, line 241](https://github.com/canton7/Simple.Migrations/blob/master/src/Simple.Migrations/SimpleMigrator%602.cs#L241) uses the `CurrentMigration` property, which is not yet updated. This causes the `to` parameter always being of the same value as the `from` parameter.

I guess that the same problem occurs with the call to `EndSequenceWithError` a few lines below.

The fix seems to be either a call to `SetCurrentVersion(version)` after every applied version - or that the version gets remembered in a local variable...

**Comment by canton7** [comment]
Thanks!

**Comment by canton7** [comment]
Fixed in v0.9.19.
