### ISSUE TITLE
Console runner should return non-zero error code when it encounters an error

### ISSUE THREAD

**Issue by ydie22** [canton7/Simple.Migrations#33]
Currently the behavior of the ConsoleRunner is to catch all exceptions and print them on the console. It would be nice that it also returns a non-zero error code that can be detected when using it unattended (think automated builds, scripts). So we can make our release fail when migrations could not be applied for whatever reason.

**Comment by canton7** [comment]
Yep, definitely.

**Comment by davidspiess** [comment]
Since the code is already written, can we expect a new release soon?

**Comment by canton7** [comment]
Crap, sorry! Slipped my radar.

**Comment by davidspiess** [comment]
Awesome, thanks! :)
