### ISSUE TITLE
Possible Functionality - Run migration from a version to a version

### ISSUE THREAD

**Issue by ahmetildirim** [canton7/Simple.Migrations#35]
It would be useful to set migrations start version and end version. Right not we can do a similar thing by setting baseline, but it requires baseline version to exist as Migration even if it doesn't run it.

**Comment by canton7** [comment]
What's the use-case? 

> Right not we can do a similar thing by setting baseline, but it requires baseline version to exist as Migration even if it doesn't run it.

This implies you would want to specify a "from" version which doesn't exist?

**Comment by canton7** [comment]
Closing as no response
