### ISSUE TITLE
Different migration version for each database schema

### ISSUE THREAD

**Issue by martilan88** [canton7/Simple.Migrations#36]
Hi, I have one database with more schemas where each schema should use the same migrations but each schema could be on a different version. For example, I have 2 schemas in my database (Schema1 and Schema2) and 5 migrations. Is it possible, so that Schema1 would be on migration 1 (i.e. CurrentMigration = 1) and Schema2 would be on migration 5 (CurrentMigration = 5)?
Thanks!

**Comment by canton7** [comment]
Since the current version is stored in the VersionInfo table, I don't see why not.

You'd need to configure the database provider to connect to one of the two schemas, but from there onwards it should just interact with that one schema, including the VersionInfo table in that schema.

**Comment by martilan88** [comment]
OK, it's working. Thanks!
