### ISSUE TITLE
swap `System.Data.SqlClient` for `Microsoft.Data.SqlClient`

### ISSUE THREAD

**Issue by JaggerJo** [canton7/Simple.Migrations#38]
As more ORMs and SQL generating libraries migrate to `Microsoft.Data.SqlClient` it gets harder to use the `System.Data.SqlConnection` with other libs for more complicated migrations.

**Comment by canton7** [comment]
I don't follow I'm afraid: I don't reference `System.Data.SqlClient` anywhere. The only thing I depend on is `System.Data.Common.DbConnection` and friends, and `Microsoft.Data.SqlClient.SqlConnection` inherits from this. Can you please be more specific? Thanks!

**Comment by JaggerJo** [comment]
Sorry for the confusion. 

Basically my problem is (and there might be a different solution to it then) that I need to execute a complex migration. To do so I want to use [DustyTables](https://github.com/Zaid-Ajaj/DustyTables) and pass the sql connection the migration classes have ([Migration.Connection](https://github.com/canton7/Simple.Migrations/blob/4655dc69a8018efe2afc1f81f0ab91db26e49158/src/Simple.Migrations/Migration.cs#L24)).

DustyTables expects a `Microsoft.Data.SqlClient.SqlConnection` and as far as I know I can't construct one with the information exposed by an `System.Data.Common.DbConnection`.

So to me it looks like I need to implement a `IDatabaseProvider<Microsoft.Data.SqlClient.SqlConnection>` instead of `IDatabaseProvider<System.Data.Common.DbConnection>` and do the same with the migration class...

**Comment by canton7** [comment]
Can't you cast the DbConnection to a SqlConnection in your migration, or am I missing something? You get to control what instance is passed into the Database Provider, and that same instance is made available to the migration.
