### ISSUE TITLE
Multiple migration base types throws exception 

### ISSUE THREAD

**Issue by MiroslavMikus** [canton7/Simple.Migrations#40]
Hey, so I'm back.

Let's start with the [example](https://github.com/MiroslavMikus/Bug.SimpleMigrations)
So [here](https://github.com/MiroslavMikus/Bug.SimpleMigrations/blob/196c0a57c09189f3d453289c33e1a188843099ed/ConsoleApp1/TextDatabaseProvider.cs#L1) is my text-based migration which implements [IMigration](https://github.com/MiroslavMikus/Bug.SimpleMigrations/blob/196c0a57c09189f3d453289c33e1a188843099ed/ConsoleApp1/TextDatabaseProvider.cs#L46)

and [here](https://github.com/MiroslavMikus/Bug.SimpleMigrations/blob/196c0a57c09189f3d453289c33e1a188843099ed/ConsoleApp1/NumberDatabaseProvider.cs#L1) is the int-based migration, also with the implementation of [IMigration](https://github.com/MiroslavMikus/Bug.SimpleMigrations/blob/196c0a57c09189f3d453289c33e1a188843099ed/ConsoleApp1/NumberDatabaseProvider.cs#L46)

Running this small program will lead into:

![image](https://user-images.githubusercontent.com/29312172/131363860-1de66503-456b-45e2-bacb-8c025cc6af6f.png)

Which is clearly not the case.

I guess some false positive somewhere in the FindAndSetMigrations [here](https://github.com/canton7/Simple.Migrations/blob/4655dc69a8018efe2afc1f81f0ab91db26e49158/src/Simple.Migrations/SimpleMigrator%602.cs#L138)

**Comment by canton7** [comment]
Well, NumberMigration implements `IMigration<NumberState>`, but this line https://github.com/MiroslavMikus/Bug.SimpleMigrations/blob/main/ConsoleApp1/Program.cs#L34 says that all migrations implement `IMigration<TextState>`.

That's your problem.

**Comment by canton7** [comment]
The exception message strips the generic type parameter, which makes the problem non-obvious. I'll fix that

**Comment by MiroslavMikus** [comment]
The problem is that I do not understand it well enough -_-

So this line says that I would like to migrate Numbers `IMigration<NumberState>`
https://github.com/MiroslavMikus/Bug.SimpleMigrations/blob/196c0a57c09189f3d453289c33e1a188843099ed/ConsoleApp1/Program.cs#L48

and this `IMigration<TextState>`

https://github.com/MiroslavMikus/Bug.SimpleMigrations/blob/main/ConsoleApp1/Program.cs#L34

They have nothing to do with each other, except that both are in the same assembly.

If I comment one of my migrations out (DatabaseProvider, Migrations...) the other one works like a charm. If I want to run both, one of them fails.

I didn't get the problem yet... Is there something I'm missing?

**Comment by MiroslavMikus** [comment]
As far as I would expect https://github.com/MiroslavMikus/Bug.SimpleMigrations/blob/main/ConsoleApp1/Program.cs#L34 says: Search in this specific assembly (`typeof(Program).Assembly`) for implementations of `IMigration<TextState>` and not for all Migrations.

**Comment by canton7** [comment]
Opps, I was on my phone and missed some context. 

See https://github.com/canton7/Simple.Migrations/blob/master/src/Simple.Migrations/AssemblyMigrationProvider.cs#L49. That just looks for the Migration attribute, and not the interface type it implements. You can provide your own which filters on the implemented interface type.

**Comment by MiroslavMikus** [comment]
That explains how do you answer so quickly :wink:

Somehow I did miss the Provider feature. 
`var provider = new AssemblyMigrationProvider(typeof(Program).Assembly, typeof(TextState).Namespace);`
Creating a new provider with the specific namespace does solve the problem as well.

Closing with the statement: It's not a bug, it's a feature!
