### ISSUE TITLE
Version in migration and database type mismatch

### ISSUE THREAD

**Issue by sparkeh9** [canton7/Simple.Migrations#9]
The Version type on MigrationAttribute is a long (or Int64), however the version field on MSSQL, MySQL and SQLite version provider is INT (PostgreSQL seems to be correct in using bigint).

This presents problems when using timestamps as version string (such as 20161116000000), as this is inserted into the database as 2147483647 due to field width.

**Comment by canton7** [comment]
Oops, good point! I'm in the middle of tearing everything apart to get concurrent migrations in, so I'm afraid fixing this will have to wait until that refactoring is done.

**Comment by canton7** [comment]
Oops, thanks for reporting! I'm afraid I'm in the middle of tearing everything apart to support concurrent migrations at the moment, so fixing this will have to wait until I've finished that refactoring.

**Comment by sparkeh9** [comment]
I created a custom version provider in light of this issue, so it's no big deal

If it's an issue of time, I am willing to submit a pull request to fix these minor points :)

**Comment by canton7** [comment]
It's more an issue that the structure of the version providers is probably going to change (so they become more generic database providers which also handle things like locking)

**Comment by canton7** [comment]
In SQLite, "INTEGER" can hold up to 8 bytes. I've fixed MSSQL and MySQL.

**Comment by canton7** [comment]
Right, v0.9.7 is out, which fixes this.
